### ISSUE TITLE
Reverse DNS does not match SMTP greeting

### ISSUE THREAD

**Issue by dengine** [dirtsimple/poste.io#10]
Hi, rdns records set correct, but after installation poste.io smtp hello command use only hello from general server ip. outbound-hosts.yaml looks good. Check this issue please. I'm not the only one with this problem.

**Comment by pjeby** [comment]
Is the outbound IP selection working?  Do the logs list the correct HELO and IP?

**Comment by pjeby** [comment]
Also, please note that outbound IP+HELO setting only occurs if you have more than one IP address on the machine.  You might want to show me your configuration here, both your docker-compose.yml or comparable file, and your outbound-hosts.yml.

(Last, but not least, the file is supposed to be called outbound-hosts.**yml**, not .yaml -- so if the IPs aren't working either, then that's likely the problem.)

**Comment by dengine** [comment]
Problem fixed. I have 20 ips, and 1 ip from server, error was in outbound-hosts.yml file. The error was my fault, everything works. thanks for the answer
