### ISSUE TITLE
Different ipv6 notation for haraka and nginx?

### ISSUE THREAD

**Issue by teejot** [dirtsimple/poste.io#12]
Hi,

I am trying to let the mailserver listen on one ipv6 address. It seems like haraka and nginx needs different notation so either nginx is working or haraka.

If I am using "LISTEN_ON=168.119.xxx.xx [2a01:4f8:xxxx:xxxx::1]" it works for haraka but not nginx and using "LISTEN_ON=168.119.xxx.x 2a01:4f8:xxxx:xxxx::1" it is working for nginx only.

I was not able to find the part in the patchfile.

Best,
Torben

**Comment by pjeby** [comment]
Try the new version (2.2.31-0.4.4): it should work without brackets now.

**Comment by teejot** [comment]
Yes, works.
