### ISSUE TITLE
Problem with sieve script

### ISSUE THREAD

**Issue by teejot** [dirtsimple/poste.io#13]
Hi,

I've found 
_Error: sieve: Failed to compile script `/etc/dovecot/sieve/report-spam.sieve'
Error: sieve: report-spam: line 2: expecting ',' or end of string list ']', but found string
Error: sieve: report-spam: parse failed_
in the logfiles.

The argument list of the pipe command of rspamc seems to be wrong and should be separated with commas like:
_pipe :copy "rspamc" ["-h", "/var/run/rspamd-web.sock", "learn_spam"];_
but I cannot get it working.
But
_pipe :copy "rspamc" ["--connect=/var/run/rspamd-web.sock", "learn_spam"];_
seems to work.

best,
Torben

**Comment by pjeby** [comment]
This should be fixed in 2.2.31-0.4.5.  Let me know if there's still a problem.
