### ISSUE TITLE
Limiting the sending speed for each recipient domain separately

### ISSUE THREAD

**Issue by rafaello9** [dirtsimple/poste.io#18]
Mr pjeby!
Last time you helped me a lot to solve my problematic question.
But I have another one.
I understand that this second question has nothing to do with your project, but
as far as possible, I ask you to give at least a direction, where to look?
Although, if you gave a full hint, it would be perfect.
All in all, I need to limit/increase the speed of sending letters for each recipient domain individually and so that it is in one sending session.
For example, for the domain @gmail.com - 10/min, @hotmail.com - 25/min, @yahoo.com - 50/min

**Comment by pjeby** [comment]
You will probably need to create your own plugin for this, as the closest thing to what you describe is the [Haraka Limits plugin](https://github.com/haraka/haraka-plugin-limit), and it does not support per-domain counts or message counts, only a global outbound connection concurrency limit per destination domain.

You will probably also need to look at the official poste.io documentation for info on adding Haraka plugins to your installation.
