### ISSUE TITLE
Update to a newer version

### ISSUE THREAD

**Issue by chmadkk** [dirtsimple/poste.io#20]
Is there any pipeline o nnew versions ?

**Comment by pjeby** [comment]
I don't know what you mean by pipeline, but I don't have any specific release dates planned unless I or my paying clients need something.

If you don't want to wait, you can simply clone this repo and edit the Dockerfile to pull a different upstream version, then `docker build` and tag the image appropriately.  Let me know if you run into any problems and I will see what needs to happen to fix them.

**Comment by pjeby** [comment]
Update: I have built a new [unstable release](https://hub.docker.com/layers/dirtsimple/poste.io/unstable/images/sha256-ee26cc43a7949f9b0ab6f7069b2d54c1e535312e93bf330edc3432e1305e1477?context=explore) that builds for 2.3.6 but is not tested in any way.  If you'd like to try it and report any issues you find, you can pull dirtsimple/poste.io:unstable and try it.

(Please note that you should not update your production environment without testing in a development environment, and that if this loses data, prevents downgrading, or any other disaster, I can't really help you.  The admin app was completely rewritten in 2.3 and there have been huge changes to how Haraka works that might affect this image's features, including the inbound/outbound IP stuff.)
