### ISSUE TITLE
Image arm v7

### ISSUE THREAD

**Issue by taimadoCE** [dirtsimple/poste.io#24]
Hi, friends. I would like to know if is possible to build this image for armv7 
Thanks.

**Comment by pjeby** [comment]
You need to ask the upstream creators - the people at poste.io.  It's not possible for us to make an arm image since the upstream image is not available for arm.

**Comment by navin-hariharan** [comment]
Arm is available! https://hub.docker.com/r/docker/dockerfile-upstream/tags

**Comment by pjeby** [comment]
No, it isn't: https://hub.docker.com/r/analogic/poste.io/tags
