### ISSUE TITLE
SMTP Error (550): Failed to add recipient "example@mydomain.com" (Error: No such user)

### ISSUE THREAD

**Issue by WilliamSoderberg** [dirtsimple/poste.io#26]
Hi,
I have a problem when trying to send a email from "ex.1@mydomain.com" to "ex.google@mydomain.com"

I have set up split delivery for Google Workplace so that I can have my main email adress : "ex.google@mydomain.com" hosted by Google and all the other adresses that are not so important self-hosted on my server.

Everything is working as intended except for when trying to send an Email from a self-hosted adress to my main one. The error showing is: SMTP Error (550): Failed to add recipient "ex.google@mydomain.com" (Error: No such user).

What I suspect is that it is trying to send the email internally and therefor not finding it because I have not added it to Poste.io. 

Is there a way to force all sent emails to go externally or bypass the Error: No such user?

**Comment by pjeby** [comment]
I have no idea.  You probably want to consult the documentation for Haraka, or else get support from the developers of poste.io -- this repository is just an enhancement layer over poste.io, which in turn is an enhancement layer over Haraka and some other things.
