### ISSUE TITLE
Support 2FA Login 

### ISSUE THREAD

**Issue by readthecodes** [dirtsimple/poste.io#29]
Please support 2fa login, or it will be hacked by password force crack, this is not acceptable for mail server.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by pjeby** [comment]
You have the wrong repository: this project is a minor set of modifications to poste.io, which is the project that does the actual mail serving.  Their issue repository is on Gitlab, not here.
