### ISSUE TITLE
Issue sending emails

### ISSUE THREAD

**Issue by lucidnx** [dirtsimple/poste.io#30]
hello! after latest update of docker version, I have issues with sending emails. Web UI show just "SMTP Error ()", Admin looks normal except Delivery quene, which is constantly loading and nothing is shown. Can you help please?

log:
```
Jan 19 20:11:56 mail01 dovecot: lmtp(7180): Connect from local
Jan 19 20:11:56 mail01 dovecot: lmtp(user@domain.tld)<7180><lcgWBozXqmUMHAAADqa4FA>: Error: smtp-client: conn 127.0.0.1:587 [1]: connect(127.0.0.1:587) failed: Connection refused
Jan 19 20:11:56 mail01 dovecot: lmtp(user@domain.tld)<7180><lcgWBozXqmUMHAAADqa4FA>: Error: sieve: msgid=<592597239-2785860@senderdomain.tld>: redirect action: failed to redirect message to <forwardrecipient@recipientdomain.tld>: smtp(127.0.0.1:587): RCPT TO failed: Failed to connect to remote server (temporary failure)
Jan 19 20:11:56 mail01 dovecot: lmtp(user@domain.tld)<7180><lcgWBozXqmUMHAAADqa4FA>: Error: sieve: Execution of script /data/domains/domain.tld/user/.dovecot.sieve was aborted due to temporary failure (user logfile /data/domains/domain.tld/user/.dovecot.sieve.log may reveal additional details)
Jan 19 20:11:56 mail01 dovecot: lmtp(7180): Disconnect from local: Logged out (state=READY)
```

**Comment by pjeby** [comment]
I don't understand what you mean by "latest update of docker version".  Do you mean you are using the `unstable`  version?  What version of this image are you using, and what is the version that shows in the admin dashboard?

**Comment by lucidnx** [comment]
> I don't understand what you mean by "latest update of docker version". Do you mean you are using the `unstable` version? What version of this image are you using, and what is the version that shows in the admin dashboard?

It's "latest" tag on dockerhub. Anyway, It is fixed by "itself" after 2 reboots. Nothing interesting in logs so I am closing this.
