### ISSUE TITLE
Port 587 unavailable

### ISSUE THREAD

**Issue by RexLee0929** [dirtsimple/poste.io#32]
![image](https://github.com/user-attachments/assets/a3ba17fe-fea5-49fd-aa74-cf1b32287590)
After I rebuilt the new version of the image, I found that port 587 is not available, using the 2.4.4 version built two or three months ago can be used, but now rebuild the 2.4.4 version can not be used, build the latest version also can not be used!

**Comment by pjeby** [comment]
Did you find out what the problem was?
