### ISSUE TITLE
Make changes

### ISSUE THREAD

**Issue by visomymail** [dirtsimple/poste.io#34]
Good afternoon, will you be able to make additions for a separate payment for your work?

We need the following functions:
- - traffic distribution by mx in the queue (yandex in one, gmail in another, etc.)
- - queue dosage (1 letter per minute)
- - queue freezing when receiving error 550 spam and deleting the queue
- - mailing from an IP pool and setting up several pools

**Comment by pjeby** [comment]
Most of those sound like they'd be changes to Haraka (the actual mail server run by poste.io); you should probably talk to the Haraka devs instead, you'd be more likely to find somebody who can do things like that for you.
