### ISSUE TITLE
Healthcheck for Redis failes

### ISSUE THREAD

**Issue by r0bb10** [dirtsimple/poste.io#4]
Hi, really nice work you did here, i just wanted you to know a little bug affecting the healthcheck of the container, redis.sh is failing because still listening at 6379 on localhost.

Keep it up and thanks!

**Comment by pjeby** [comment]
I don't understand; what health check are you doing?  The server status and connection diagnostics in the admin dashboard all look fine to me, and my servers aren't listening on localhost:6379.

**Comment by pjeby** [comment]
Never mind; I figured it out.  Fixed in 3e3d73ef8 and rolling out as 2.2.19-0.4.1.
