### ISSUE TITLE
how to change password?

### ISSUE THREAD

**Issue by njavilas** [dirtsimple/poste.io#8]
Hello how to change password?

**Comment by njavilas** [comment]
password from roundcube in users

**Comment by pjeby** [comment]
All user management is done through the poste.io admin screens, including password changes.  In principle you could set up the roundcube password change plugin with the appropriate settings to allow mailbox users to change their own passwords, but I can't give you any help with that as I have never done it myself and don't have any plans to.

**Comment by njavilas** [comment]
I appreciate the help, I tried to change it from roundcube but there are problems with php running the post binary I'm looking at installing my own server and meanwhile using this, I want to be able to see it together with the services we offer
