### ISSUE TITLE
Every 1 minute recieve than email from root to admin user

### ISSUE THREAD

**Issue by torbikua** [dirtsimple/poste.io#9]
I don't know how to fix it

```
From: root@localhost
Cron <root@relay> /bin/clear-idle-connections 
От root за 2021-05-02 12:16
Подробности
PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "'/usr/bin/redis-cli' 'CLIENT' 'LIST'" failed.

Exit Code: 1(General error)

Working directory: /root

Output:
================


Error Output:
================
Could not connect to Redis at 127.0.0.1:6379: Connection refused
 in /opt/admin/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:235
Stack trace:
#0 /bin/clear-idle-connections(10): Symfony\Component\Process\Process->mustRun()
#1 {main}
  thrown in /opt/admin/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php on line 235
```

**Comment by pjeby** [comment]
This is now fixed in 2.2.7-0.4.3.  The patches didn't cover the auxiliary files.  You should be able to pull a new image shortly.

**Comment by akuryzhev** [comment]
The same problem.
analogic/poste.io:latest

Every 1min revised this message:

PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "'/usr/bin/redis-cli' 'CLIENT' 'LIST'" failed.

Exit Code: 1(General error)

Working directory: /root

Output:
================


Error Output:
================
Could not connect to Redis at 127.0.0.1:6379: Connection refused
 in /opt/admin/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:235
Stack trace:
#0 /bin/clear-idle-connections(10): Symfony\Component\Process\Process->mustRun()
#1 {main}
  thrown in /opt/admin/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php on line 235

**Comment by pjeby** [comment]
I don't understand -- you're mentioning analogic/poste.io, but this is the repository for dirtsimple/poste.io.  If it's the analogic version, mentioning it here will not help since we do not control that version.  If this is an issue you're having with the dirtsimple/poste.io image, then please check and make sure you are using 2.2.27-0.4.3 or higher.  (The latest is 2.2.32-0.4.5.)

(Note that "latest" doesn't really mean anything except that it is the "latest" version you have installed on your machine.  If you installed an image six month ago it could be tagged "latest" on your machine even though many versions have been released since then.)

**Comment by akuryzhev** [comment]
> I don't understand -- you're mentioning analogic/poste.io, but this is the repository for dirtsimple/poste.io. If it's the analogic version, mentioning it here will not help since we do not control that version. If this is an issue you're having with the dirtsimple/poste.io image, then please check and make sure you are using 2.2.27-0.4.3 or higher. (The latest is 2.2.32-0.4.5.)
> 
> (Note that "latest" doesn't really mean anything except that it is the "latest" version you have installed on your machine. If you installed an image six month ago it could be tagged "latest" on your machine even though many versions have been released since then.)

Oh, really. Sorry, I have used another version of poste.io
I will try dirtsimple/poste.io. Thank you
